version: '2'
services:
  polymer:
    image: daveslab/development:polymer
    command: /bin/bash /docker/provision/polymer.bash
    ports:
         - "8082:8082"
    volumes:
      - .:/docker
      - ~/.ssh/id_rsa:/root/.ssh/id_rsa
    tty: true
    restart: always
